/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyEventsIndexRouteImport } from './routes/my-events/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MyEventsEventIdRouteImport } from './routes/my-events/$eventId'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as AdminResponsesRouteImport } from './routes/admin/responses'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events.$eventId'
import { Route as EventsEventIdEditEditTokenRouteImport } from './routes/events/$eventId/edit/$editToken'
import { Route as EventsEventIdAdminAdminTokenRouteImport } from './routes/events/$eventId/admin/$adminToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsIndexRoute = MyEventsIndexRouteImport.update({
  id: '/my-events/',
  path: '/my-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsEventIdRoute = MyEventsEventIdRouteImport.update({
  id: '/my-events/$eventId',
  path: '/my-events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/admin/responses',
  path: '/admin/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminEventsRoute,
} as any)
const EventsEventIdEditEditTokenRoute =
  EventsEventIdEditEditTokenRouteImport.update({
    id: '/events/$eventId/edit/$editToken',
    path: '/events/$eventId/edit/$editToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdAdminAdminTokenRoute =
  EventsEventIdAdminAdminTokenRouteImport.update({
    id: '/events/$eventId/admin/$adminToken',
    path: '/events/$eventId/admin/$adminToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/events/create': typeof EventsCreateRoute
  '/my-events/$eventId': typeof MyEventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/my-events': typeof MyEventsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/events/create': typeof EventsCreateRoute
  '/my-events/$eventId': typeof MyEventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/my-events': typeof MyEventsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/logs': typeof AdminLogsRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/events/create': typeof EventsCreateRoute
  '/my-events/$eventId': typeof MyEventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-events/': typeof MyEventsIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/responses'
    | '/events/create'
    | '/my-events/$eventId'
    | '/admin'
    | '/my-events'
    | '/admin/events/$eventId'
    | '/events/$eventId'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/responses'
    | '/events/create'
    | '/my-events/$eventId'
    | '/admin'
    | '/my-events'
    | '/admin/events/$eventId'
    | '/events/$eventId'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/responses'
    | '/events/create'
    | '/my-events/$eventId'
    | '/admin/'
    | '/my-events/'
    | '/admin/events/$eventId'
    | '/events/$eventId/'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminLogsRoute: typeof AdminLogsRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  EventsCreateRoute: typeof EventsCreateRoute
  MyEventsEventIdRoute: typeof MyEventsEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MyEventsIndexRoute: typeof MyEventsIndexRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdAdminAdminTokenRoute: typeof EventsEventIdAdminAdminTokenRoute
  EventsEventIdEditEditTokenRoute: typeof EventsEventIdEditEditTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events/': {
      id: '/my-events/'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events/$eventId': {
      id: '/my-events/$eventId'
      path: '/my-events/$eventId'
      fullPath: '/my-events/$eventId'
      preLoaderRoute: typeof MyEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/admin/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/events/$eventId/edit/$editToken': {
      id: '/events/$eventId/edit/$editToken'
      path: '/events/$eventId/edit/$editToken'
      fullPath: '/events/$eventId/edit/$editToken'
      preLoaderRoute: typeof EventsEventIdEditEditTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/admin/$adminToken': {
      id: '/events/$eventId/admin/$adminToken'
      path: '/events/$eventId/admin/$adminToken'
      fullPath: '/events/$eventId/admin/$adminToken'
      preLoaderRoute: typeof EventsEventIdAdminAdminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminLogsRoute: AdminLogsRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  EventsCreateRoute: EventsCreateRoute,
  MyEventsEventIdRoute: MyEventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MyEventsIndexRoute: MyEventsIndexRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdAdminAdminTokenRoute: EventsEventIdAdminAdminTokenRoute,
  EventsEventIdEditEditTokenRoute: EventsEventIdEditEditTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
