/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdEditEditTokenRouteImport } from './routes/events/$eventId/edit/$editToken'
import { Route as EventsEventIdAdminAdminTokenRouteImport } from './routes/events/$eventId/admin/$adminToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditEditTokenRoute =
  EventsEventIdEditEditTokenRouteImport.update({
    id: '/events/$eventId/edit/$editToken',
    path: '/events/$eventId/edit/$editToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdAdminAdminTokenRoute =
  EventsEventIdAdminAdminTokenRouteImport.update({
    id: '/events/$eventId/admin/$adminToken',
    path: '/events/$eventId/admin/$adminToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/admin/$adminToken': typeof EventsEventIdAdminAdminTokenRoute
  '/events/$eventId/edit/$editToken': typeof EventsEventIdEditEditTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/create'
    | '/events/$eventId'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/create'
    | '/events/$eventId'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  id:
    | '__root__'
    | '/'
    | '/events/create'
    | '/events/$eventId/'
    | '/events/$eventId/admin/$adminToken'
    | '/events/$eventId/edit/$editToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdAdminAdminTokenRoute: typeof EventsEventIdAdminAdminTokenRoute
  EventsEventIdEditEditTokenRoute: typeof EventsEventIdEditEditTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit/$editToken': {
      id: '/events/$eventId/edit/$editToken'
      path: '/events/$eventId/edit/$editToken'
      fullPath: '/events/$eventId/edit/$editToken'
      preLoaderRoute: typeof EventsEventIdEditEditTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/admin/$adminToken': {
      id: '/events/$eventId/admin/$adminToken'
      path: '/events/$eventId/admin/$adminToken'
      fullPath: '/events/$eventId/admin/$adminToken'
      preLoaderRoute: typeof EventsEventIdAdminAdminTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdAdminAdminTokenRoute: EventsEventIdAdminAdminTokenRoute,
  EventsEventIdEditEditTokenRoute: EventsEventIdEditEditTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
